name: "Supported Services Matrix Calculator"
author: "Mage-OS"
description: "Calulate a matrix of all supported services (based off supported-services.json)"

inputs:
  repository:
    type: string
    description: "Repository"
    required: true
  ref:
    type: string
    description: "head SHA"
    required: true

outputs:
  php_versions: 
    description: The applicable PHP versions
    value: ${{ steps.set-matrix.outputs.php_versions }}
  database_versions: 
    description: The applicable DB versions
    value: ${{ steps.set-matrix.outputs.database_versions }}
  search_versions: 
    description: The applicable Search versions
    value: ${{ steps.set-matrix.outputs.search_versions }}
  message_queue_versions: 
    description: The applicable Message Queue versions
    value: ${{ steps.set-matrix.outputs.message_queue_versions }}
  cache_versions: 
    description: The applicable Cache versions
    value: ${{ steps.set-matrix.outputs.cache_versions }}
  http_cache_versions: 
    description: The applicable HTTP Cache versions
    value: ${{ steps.set-matrix.outputs.http_cache_versions }}

runs:
  using: "composite"
  steps:

    - id: set-matrix
      name: Calculate Matrix
      shell: bash
      run: |
        echo 'php_versions=[7.4, 8.2]' >> "$GITHUB_OUTPUT"
        echo 'database_versions=[1.0]' >> "$GITHUB_OUTPUT"
        echo 'search_versions=[1.0]' >> "$GITHUB_OUTPUT"
        echo 'message_queue_versions=[1.0]' >> "$GITHUB_OUTPUT"
        echo 'cache_versions=[1.0]' >> "$GITHUB_OUTPUT"
        echo 'http_cache_versions=[1.0]' >> "$GITHUB_OUTPUT"

    - name: Debug output
      shell: bash
      run: |
        echo "PHP Versions: ${{ steps.set-matrix.outputs.php_versions }}"
        echo "database Versions: ${{ steps.set-matrix.outputs.database_versions }}"
        echo "search Versions: ${{ steps.set-matrix.outputs.search_versions }}"
        echo "message_queue Versions: ${{ steps.set-matrix.outputs.message_queue_versions }}"
        echo "cache Versions: ${{ steps.set-matrix.outputs.cache_versions }}"
        echo "http_cache Versions: ${{ steps.set-matrix.outputs.http_cache_versions }}"