name: Infra workflow
on:
  workflow_call:
    inputs:
      repository:
        type: string
        description: "Repository"
        required: true
      pr_head:
        type: string
        description: "head SHA"
        required: true
      pr_base:
        type: string
        description: "pr base SHA"
        required: true
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: "Repository"
        required: true
      pr_head:
        type: string
        description: "head SHA"
        required: true
      pr_base:
        type: string
        description: "pr base SHA"
        required: true
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: debug
        shell: bash
        env:
          repository: ${{ inputs.repository }}
          pr_head: ${{ inputs.pr_head }}
          pr_base: ${{ inputs.pr_base }}
        run: |
          echo "input was"
          echo "repository: ${repository}"
          echo "pr_head: ${pr_head}"
          echo "pr_base: ${pr_base}"

  matrix-calculator:
    outputs:
      php_versions: ${{ steps.calculate-matrix.outputs.php_versions }}
      database_versions: ${{ steps.calculate-matrix.outputs.database_versions }}
      search_versions: ${{ steps.calculate-matrix.outputs.search_versions }}
      message_queue_versions: ${{ steps.calculate-matrix.outputs.message_queue_versions }}
      cache_versions: ${{ steps.calculate-matrix.outputs.cache_versions }}
      http_cache_versions: ${{ steps.calculate-matrix.outputs.http_cache_versions }}

    runs-on: ubuntu-latest
    steps:
      - name: Run Matrix Calulator
        id: calculate-matrix
        uses:  adamzero1/temp-repo/actions/matrix-calculator@main
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.pr_head }}

      - name: Calculated Result
        shell: bash
        env:
          php_versions: ${{ steps.calculate-matrix.outputs.php_versions }}
          database_versions: ${{ steps.calculate-matrix.outputs.database_versions }}
          search_versions: ${{ steps.calculate-matrix.outputs.search_versions }}
          message_queue_versions: ${{ steps.calculate-matrix.outputs.message_queue_versions }}
          cache_versions: ${{ steps.calculate-matrix.outputs.cache_versions }}
          http_cache_versions: ${{ steps.calculate-matrix.outputs.http_cache_versions }}
        run: |
          echo "PHP Versions: $php_versions"
          echo "database_versions: $database_versions"
          echo "search_versions: $search_versions"
          echo "message_queue_versions: $message_queue_versions"
          echo "cache_versions: $cache_versions"
          echo "http_cache_versions: $http_cache_versions"

  nx-project-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Run Nx Project Setup
        uses: adamzero1/temp-repo/actions/setup-project@main
      
  integration-tests:
    needs: 
      - matrix-calculator
      - nx-project-setup
    strategy:
      fail-fast: false
      matrix:
        php_version: ${{ fromJSON(needs.matrix-calculator.outputs.php_versions) }}
        database_version: ${{ fromJSON(needs.matrix-calculator.outputs.database_versions) }}
        search_version: ${{ fromJSON(needs.matrix-calculator.outputs.search_versions) }}
        message_queue_version: ${{ fromJSON(needs.matrix-calculator.outputs.message_queue_versions) }}
        cache_version: ${{ fromJSON(needs.matrix-calculator.outputs.cache_versions) }}
        http_cache_version: ${{ fromJSON(needs.matrix-calculator.outputs.http_cache_versions) }}
    runs-on: ubuntu-latest
    steps:
      - name: Running With
        shell: bash
        run: |
          echo "PHP Versions: ${{ matrix.php_version }}"
          echo "database Versions: ${{ matrix.database_version }}"
          echo "search Versions: ${{ matrix.search_version }}"
          echo "message_queue Versions: ${{ matrix.message_queue_version }}"
          echo "cache Versions: ${{ matrix.cache_version }}"
          echo "http_cache Versions: ${{ matrix.http_cache_version }}"

      - name: Running With 2nd Step
        shell: bash
        run: |
          echo "PHP Versions: ${{ matrix.php_version }}"
          echo "database Versions: ${{ matrix.database_version }}"
          echo "search Versions: ${{ matrix.search_version }}"
          echo "message_queue Versions: ${{ matrix.message_queue_version }}"
          echo "cache Versions: ${{ matrix.cache_version }}"
          echo "http_cache Versions: ${{ matrix.http_cache_version }}"
          exit 123