name: Unit Tests
run-name: ${{ github.actor }} is running Unit Tests
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        php_version: [8.1,8.2]
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "foooooo"
