name: Unit Tests
run-name: ${{ github.actor }} is running Unit Tests
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-unit-tests:
    uses: adamzero1/temp-repo2/.github/workflows/mageos-unit-tests.yml@remote-workflow