name: Unit Tests
run-name: ${{ github.actor }} is running Unit Tests
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  matrix-calculator:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.result }}
    steps:
      - name: Checkout PR commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: main
          fetch-depth: 0

      - uses: actions/github-script@v6
        id: set-matrix
        with:
          script: |
            return [8.11, 8.21]

      - name: Debug output
        run: echo "${{ steps.set-matrix.outputs.result }}"
    
  unit-tests:
    needs: matrix-calculator
    strategy:
      fail-fast: false
      matrix:
        php_version: ${{ fromJSON(needs.matrix-calculator.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "foooooo: ${{ matrix.php_version }}"
